### ISSUE TITLE
stats.xml is invalid XML

### ISSUE THREAD

**Issue by reckart** [UniversalDependencies/UD_Finnish-FTB#1]
The stats.xml file is not a valid XML file:

```
    <tag name="PUNCT">22565</tag><!-- ., ,, ?, ", !, -, :, ..., --, ; -->
```

A `--` may not appear in an XML comment

Observed in UD Treebank  v 1.3.

**Comment by jpiitula** [comment]
Richard Eckart de Castilho notifications@github.com writes:

> The stats.xml file is not a valid XML file:
> 
> ```
>     <tag name="PUNCT">22565</tag>
> ```
> 
> A `--` may not appear in an XML comment
> 
> Observed in UD Treebank  v 1.3.

That file is generated by some script. Should I still edit it by hand?

Also, how exactly should I edit it? Does &#45;&#45; make any sense in a
comment?

**Comment by fginter** [comment]
These files are generated by @danzeman. Don't edit by hand.

**Comment by jpiitula** [comment]
Filip Ginter notifications@github.com writes:

> These files are generated by @danzeman. Don't edit by hand.

All right. Thanks.

**Comment by dan-zeman** [comment]
Fixed in dev branch.
